# Generated by Django 5.1.2 on 2024-10-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_authors_remove_book_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_year',
            field=models.IntegerField(null=True),
        ),
    ]
